import { Customer } from "./RecentBookingsTable";

export const customerTableData: Customer[] = [
  {
    customerName: "John Doe",
    image: "https://i.pravatar.cc/150?u=John Doe",
    city: "United State",
    customerId: "#1245645",
    services: "Gel Manicure",
    joinDate: "May 15, 2025",
    time: "10:30 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Jane Smith",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Jane Smith",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "02:15 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Michael Johnson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Michael Johnson",
    city: "United State",
    services: "Nail Art Design",
    joinDate: "May 15, 2025",
    time: "11:45 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Emily Davis",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Emily Davis",
    city: "United State",
    services: "Classic Manicure",
    joinDate: "May 15, 2025",
    time: "03:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Robert Wilson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Robert Wilson",
    city: "United State",
    services: "Gel Manicure",
    joinDate: "May 15, 2025",
    time: "09:30 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Olivia Brown",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Olivia Brown",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "04:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "William Martinez",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=William Martinez",
    city: "United State",
    services: "Nail Art Design",
    joinDate: "May 15, 2025",
    time: "12:30 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Sophia Anderson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Sophia Anderson",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "11:15 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Daniel Thomas",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Daniel Thomas",
    city: "United State",
    services: "Gel Manicure",
    joinDate: "May 15, 2025",
    time: "01:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Ava Jackson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Ava Jackson",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "05:45 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "James White",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=James White",
    city: "United State",
    services: "Classic Manicure",
    joinDate: "May 15, 2025",
    time: "09:15 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Isabella Harris",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Isabella Harris",
    city: "United State",
    services: "Classic Manicure",
    joinDate: "May 15, 2025",
    time: "03:30 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Benjamin Clark",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Benjamin Clark",
    city: "United State",
    services: "Haircut",
    joinDate: "May 15, 2025",
    time: "10:00 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Mia Lewis",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Mia Lewis",
    city: "United State",
    services: "Facial",
    joinDate: "May 15, 2025",
    time: "01:45 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Elijah Walker",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Elijah Walker",
    city: "United State",
    services: "Beard Trim",
    joinDate: "May 15, 2025",
    time: "04:30 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Charlotte Hall",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Charlotte Hall",
    city: "United State",
    services: "Nail Care",
    joinDate: "May 15, 2025",
    time: "11:45 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Henry Allen",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Henry Allen",
    city: "United State",
    services: "Massage",
    joinDate: "May 15, 2025",
    time: "03:15 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Amelia Young",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=johndoe",
    city: "United State",
    services: "Spa Treatment",
    joinDate: "May 15, 2025",
    time: "09:00 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Lucas King",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Lucas King",
    city: "United State",
    services: "Haircut",
    joinDate: "May 15, 2025",
    time: "02:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Harper Scott",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Harper Scott",
    city: "United State",
    services: "Facial",
    joinDate: "May 15, 2025",
    time: "05:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "John Doe",
    image: "https://i.pravatar.cc/150?u=John Doe",
    city: "United State",
    customerId: "#1245645",
    services: "Gel Manicure",
    joinDate: "May 15, 2025",
    time: "10:30 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Jane Smith",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Jane Smith",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "02:15 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Michael Johnson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Michael Johnson",
    city: "United State",
    services: "Nail Art Design",
    joinDate: "May 15, 2025",
    time: "11:45 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Emily Davis",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Emily Davis",
    city: "United State",
    services: "Classic Manicure",
    joinDate: "May 15, 2025",
    time: "03:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Robert Wilson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Robert Wilson",
    city: "United State",
    services: "Gel Manicure",
    joinDate: "May 15, 2025",
    time: "09:30 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Olivia Brown",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Olivia Brown",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "04:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "William Martinez",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=William Martinez",
    city: "United State",
    services: "Nail Art Design",
    joinDate: "May 15, 2025",
    time: "12:30 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Sophia Anderson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Sophia Anderson",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "11:15 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Daniel Thomas",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Daniel Thomas",
    city: "United State",
    services: "Gel Manicure",
    joinDate: "May 15, 2025",
    time: "01:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Ava Jackson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Ava Jackson",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "05:45 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "James White",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=James White",
    city: "United State",
    services: "Classic Manicure",
    joinDate: "May 15, 2025",
    time: "09:15 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Isabella Harris",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Isabella Harris",
    city: "United State",
    services: "Classic Manicure",
    joinDate: "May 15, 2025",
    time: "03:30 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Benjamin Clark",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Benjamin Clark",
    city: "United State",
    services: "Haircut",
    joinDate: "May 15, 2025",
    time: "10:00 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Mia Lewis",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Mia Lewis",
    city: "United State",
    services: "Facial",
    joinDate: "May 15, 2025",
    time: "01:45 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Elijah Walker",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Elijah Walker",
    city: "United State",
    services: "Beard Trim",
    joinDate: "May 15, 2025",
    time: "04:30 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Charlotte Hall",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Charlotte Hall",
    city: "United State",
    services: "Nail Care",
    joinDate: "May 15, 2025",
    time: "11:45 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Henry Allen",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Henry Allen",
    city: "United State",
    services: "Massage",
    joinDate: "May 15, 2025",
    time: "03:15 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Amelia Young",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=johndoe",
    city: "United State",
    services: "Spa Treatment",
    joinDate: "May 15, 2025",
    time: "09:00 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Lucas King",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Lucas King",
    city: "United State",
    services: "Haircut",
    joinDate: "May 15, 2025",
    time: "02:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Harper Scott",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Harper Scott",
    city: "United State",
    services: "Facial",
    joinDate: "May 15, 2025",
    time: "05:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "John Doe",
    image: "https://i.pravatar.cc/150?u=John Doe",
    city: "United State",
    customerId: "#1245645",
    services: "Gel Manicure",
    joinDate: "May 15, 2025",
    time: "10:30 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Jane Smith",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Jane Smith",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "02:15 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Michael Johnson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Michael Johnson",
    city: "United State",
    services: "Nail Art Design",
    joinDate: "May 15, 2025",
    time: "11:45 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Emily Davis",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Emily Davis",
    city: "United State",
    services: "Classic Manicure",
    joinDate: "May 15, 2025",
    time: "03:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Robert Wilson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Robert Wilson",
    city: "United State",
    services: "Gel Manicure",
    joinDate: "May 15, 2025",
    time: "09:30 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Olivia Brown",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Olivia Brown",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "04:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "William Martinez",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=William Martinez",
    city: "United State",
    services: "Nail Art Design",
    joinDate: "May 15, 2025",
    time: "12:30 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Sophia Anderson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Sophia Anderson",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "11:15 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Daniel Thomas",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Daniel Thomas",
    city: "United State",
    services: "Gel Manicure",
    joinDate: "May 15, 2025",
    time: "01:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Ava Jackson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Ava Jackson",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "05:45 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "James White",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=James White",
    city: "United State",
    services: "Classic Manicure",
    joinDate: "May 15, 2025",
    time: "09:15 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Isabella Harris",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Isabella Harris",
    city: "United State",
    services: "Classic Manicure",
    joinDate: "May 15, 2025",
    time: "03:30 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Benjamin Clark",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Benjamin Clark",
    city: "United State",
    services: "Haircut",
    joinDate: "May 15, 2025",
    time: "10:00 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Mia Lewis",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Mia Lewis",
    city: "United State",
    services: "Facial",
    joinDate: "May 15, 2025",
    time: "01:45 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Elijah Walker",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Elijah Walker",
    city: "United State",
    services: "Beard Trim",
    joinDate: "May 15, 2025",
    time: "04:30 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Charlotte Hall",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Charlotte Hall",
    city: "United State",
    services: "Nail Care",
    joinDate: "May 15, 2025",
    time: "11:45 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Henry Allen",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Henry Allen",
    city: "United State",
    services: "Massage",
    joinDate: "May 15, 2025",
    time: "03:15 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Amelia Young",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=johndoe",
    city: "United State",
    services: "Spa Treatment",
    joinDate: "May 15, 2025",
    time: "09:00 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Lucas King",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Lucas King",
    city: "United State",
    services: "Haircut",
    joinDate: "May 15, 2025",
    time: "02:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Harper Scott",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Harper Scott",
    city: "United State",
    services: "Facial",
    joinDate: "May 15, 2025",
    time: "05:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "John Doe",
    image: "https://i.pravatar.cc/150?u=John Doe",
    city: "United State",
    customerId: "#1245645",
    services: "Gel Manicure",
    joinDate: "May 15, 2025",
    time: "10:30 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Jane Smith",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Jane Smith",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "02:15 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Michael Johnson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Michael Johnson",
    city: "United State",
    services: "Nail Art Design",
    joinDate: "May 15, 2025",
    time: "11:45 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Emily Davis",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Emily Davis",
    city: "United State",
    services: "Classic Manicure",
    joinDate: "May 15, 2025",
    time: "03:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Robert Wilson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Robert Wilson",
    city: "United State",
    services: "Gel Manicure",
    joinDate: "May 15, 2025",
    time: "09:30 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Olivia Brown",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Olivia Brown",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "04:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "William Martinez",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=William Martinez",
    city: "United State",
    services: "Nail Art Design",
    joinDate: "May 15, 2025",
    time: "12:30 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Sophia Anderson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Sophia Anderson",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "11:15 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Daniel Thomas",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Daniel Thomas",
    city: "United State",
    services: "Gel Manicure",
    joinDate: "May 15, 2025",
    time: "01:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Ava Jackson",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Ava Jackson",
    city: "United State",
    services: "Pedicure Deluxe",
    joinDate: "May 15, 2025",
    time: "05:45 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "James White",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=James White",
    city: "United State",
    services: "Classic Manicure",
    joinDate: "May 15, 2025",
    time: "09:15 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Isabella Harris",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Isabella Harris",
    city: "United State",
    services: "Classic Manicure",
    joinDate: "May 15, 2025",
    time: "03:30 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Benjamin Clark",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Benjamin Clark",
    city: "United State",
    services: "Haircut",
    joinDate: "May 15, 2025",
    time: "10:00 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Mia Lewis",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Mia Lewis",
    city: "United State",
    services: "Facial",
    joinDate: "May 15, 2025",
    time: "01:45 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Elijah Walker",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Elijah Walker",
    city: "United State",
    services: "Beard Trim",
    joinDate: "May 15, 2025",
    time: "04:30 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Charlotte Hall",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Charlotte Hall",
    city: "United State",
    services: "Nail Care",
    joinDate: "May 15, 2025",
    time: "11:45 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Henry Allen",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Henry Allen",
    city: "United State",
    services: "Massage",
    joinDate: "May 15, 2025",
    time: "03:15 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
  {
    customerName: "Amelia Young",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=johndoe",
    city: "United State",
    services: "Spa Treatment",
    joinDate: "May 15, 2025",
    time: "09:00 AM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Lucas King",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Lucas King",
    city: "United State",
    services: "Haircut",
    joinDate: "May 15, 2025",
    time: "02:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "active",
  },
  {
    customerName: "Harper Scott",
    customerId: "#1245645",
    image: "https://i.pravatar.cc/150?u=Harper Scott",
    city: "United State",
    services: "Facial",
    joinDate: "May 15, 2025",
    time: "05:00 PM",
    contact: {
      phone: "(917) 339-6416",
      email: "Jerryhelfer43@gmail.com",
    },
    status: "inactive",
  },
];
